name: My awesome readme
on:
  workflow_dispatch:
  schedule:
    # Runs at 12 am UTC
    - cron: '0 4 1,15 * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
            # Runs a set of commands using the runners shell
      - name: Run a one-line script
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        
      - name: Update README.md
        run: |
          echo -e "# prayer-times-app-update \n Automate the update of ICCT APP TODAYS_DATE=$NOW" > README.md
          cat README.md
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Automated report"
          git push
